source 'https://rubygems.org'

ruby '3.4.4'

gem 'rails', '~> 8.0.0'
gem 'sqlite3', '>= 2.1'
gem 'puma', '~> 6.0'
gem 'bcrypt', '~> 3.1'
gem 'rack-cors'
gem 'active_model_serializers', '~> 0.10'
gem 'bootsnap', require: false

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'byebug'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'simplecov'
  gem 'rspec-retry'
  gem 'webdrivers'
  gem 'rspec-benchmark'
  gem 'test-prof'
end

group :development do
  gem 'listen'
  gem 'spring'
end
